version: '2'

tasks:
  CookDevelAssets:
    cmds:
      - mkdir -p resources/cooked
      - cp -av resources/images/* resources/cooked/
      - sass --style=expanded
             --load-path resources/stylesheets
             resources/stylesheets/styles.scss resources/cooked/styles.css