[application]
  environment = "development"
  httpPort = 8080

[resources]
  path = "resources"

[authentication]
  [authentication.nullauth]
    coreImplementation = "null"
    friendlyName = "No validation"

  [authentication.github]
    coreImplementation = "oauth"
    friendlyName = "GitHub"

[secrets]
  COOKIE_STORE_SECRET = "ChangeMe!!!"