[application]
  environment = "development"
  resourcesPath = "resources"

  [[http]]
    port = 8080

  [[auth]]
    [[github]]
      coreImplementation = "oauth"

  [[secrets]]
    COOKIE_STORE_SECRET = "ChangeMe!!!"