[application]
  environment = "development"
  httpPort = 8080

[resources]
  path = "resources"

[authentication]
  [authentication.nullauth]
    coreImplementation = "null"

[secrets]
  COOKIE_STORE_SECRET = "ChangeMe!!!"